apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  labels:
{{ include "labels" $ | indent 4 }}
  annotations:
{{ include "annotations" $ | indent 4 }}
    appComponent: Wazuh-Worker-StatefulSet
spec:
  replicas: {{ .Values.wazuh.worker_replicas }}
  selector:
    matchLabels:
      app: {{ include "appIdentifier" .Values.identifier }}-manager-svc
      node-type: worker
  serviceName: {{ include "appIdentifier" .Values.identifier }}-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
{{ include "labels" $ | indent 8 }}
        app: {{ include "appIdentifier" .Values.identifier }}-manager-svc
        node-type: worker
      name: wazuh-manager-worker
      annotations:
{{ include "annotations" $ | indent 8 }}
        secret.reloader.stakater.com/reload: "indexer-certs"
        configmap.reloader.stakater.com/reload: "{{ template "wazuh.fullname" . }}-worker-config"
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "appIdentifier" .Values.identifier }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: config
          configMap:
            name: {{ template "wazuh.fullname" . }}-worker-config
            defaultMode: 0777
        - name: filebeat-certs
          secret:
            secretName: indexer-certs
        - emptyDir: {}
          name: result-config

      securityContext:
        fsGroup: 101
      initContainers:
        - name: init-manager-cluster
          image: jakubsacha/docker-xmlstarlet
          command: ['sh',
                    '-c',
                    '/script.sh wazuh-manager-master {{ .Values.wazuh.worker_replicas }} {{ .Values.wazuh.service.ports.agentEvents }} {{ .Values.wazuh.service.ports.registration }} {{ .Values.wazuh.service.ports.wazuhInternal }} {{ .Values.wazuh.key }} {{ include "appIdentifier" .Values.identifier }}-cluster' ]
          volumeMounts:
            - mountPath: /ossec.conf
              name: config
              readOnly: true
              subPath: worker.conf
          {{- if .Values.wazuh.workercustom_config }}
            - mountPath: /ossec-addon.conf
              name: config
              readOnly: true
              subPath: worker-addon.conf
          {{- end }}
            - mountPath: /wazuh-config-mount/etc/
              name: result-config
            - mountPath: /script.sh
              name: config
              readOnly: true
              subPath: script.sh
            - mountPath: /api.yaml
              name: config
              readOnly: true
              subPath: api.yaml
            - mountPath: /var/ossec/api/configuration
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/api/configuration
            - mountPath: /var/ossec/integrations
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/integrations
      containers:
        - name: wazuh-manager
          image: "{{ .Values.wazuh.images.repository }}:{{ .Values.wazuh.images.tag }}"
          resources:
{{ toYaml .Values.wazuh.images.worker_resources | indent 12 }}
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - mountPath: /wazuh-config-mount/etc/
              name: result-config
            {{- if .Values.wazuh.local_internal_options_worker }}
            - mountPath: /wazuh-config-mount/etc/local_internal_options.conf
              name: config
              readOnly: true
              subPath: local_internal_options.conf
            {{- end }}
            - mountPath: /etc/ssl/root-ca.pem
              name: filebeat-certs
              readOnly: true
              subPath: root-ca.pem
            - mountPath: /etc/ssl/filebeat.pem
              name: filebeat-certs
              readOnly: true
              subPath: filebeat.pem
            - mountPath: /etc/ssl/filebeat.key
              name: filebeat-certs
              readOnly: true
              subPath: filebeat-key.pem
            - mountPath: /var/ossec/api/configuration
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/api/configuration
            - mountPath: /var/ossec/etc
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/etc
            - mountPath: /var/ossec/logs
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/logs
            - mountPath: /var/ossec/queue
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/queue
            - mountPath: /var/ossec/var/multigroups
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/var/multigroups
            - mountPath: /var/ossec/integrations
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/integrations
            - mountPath: /var/ossec/active-response/bin
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/active-response/bin
            - mountPath: /var/ossec/agentless
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/agentless
            - mountPath: /var/ossec/wodles
              name: wazuh-manager-worker
              subPath: wazuh/var/ossec/wodles
            - mountPath: /etc/filebeat
              name: wazuh-manager-worker
              subPath: filebeat/etc/filebeat
            - mountPath: /var/lib/filebeat
              name: wazuh-manager-worker
              subPath: filebeat/var/lib/filebeat
          ports:
            - containerPort: {{ .Values.wazuh.service.ports.agentEvents }}
              name: agents-events
            - containerPort: {{ .Values.wazuh.service.ports.wazuhInternal }}
              name: cluster
            {{- if .Values.wazuh.syslog_enable }}
            - containerPort: 514
              name: syslog
            {{- end }}
          env:
            - name: INDEXER_URL
              value: {{ .Values.dashboard.env.INDEXER_URL | quote }}
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: indexer-cred
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: indexer-cred
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: {{ .Values.wazuh.env.FILEBEAT_SSL_VERIFICATION_MODE | quote }}
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: /etc/ssl/root-ca.pem
            - name: SSL_CERTIFICATE
              value: /etc/ssl/filebeat.pem
            - name: SSL_KEY
              value: /etc/ssl/filebeat.key
            - name: WAZUH_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: wazuh-cluster-key
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-worker
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.wazuh.storageSizeWorker }}
        storageClassName: {{ .Values.wazuh.storageClassNameWorker }}
